apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: cssh
spec:
  caveats: |
    This plugin needs the following programs:
    * tmux
  description: |
    This plugin allows users to SSH into one more more Kubernetes nodes
    within separate tmux panes.
  homepage: https://github.com/containership/kubectl-cssh
  platforms:
  - bin: kubectl-cssh
    files:
    - from: ./*/parse-args.sh
      to: .
    - from: ./*/kubectl-cssh
      to: .
    - from: ./*/LICENSE
      to: .
    selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    sha256: 207cf5c1cf947183851b51f6a3afdb7ed9e98e52d49e49b76c74d3f5845e452b
    uri: https://github.com/containership/kubectl-cssh/archive/v1.0.1.tar.gz
  shortDescription: SSH into Kubernetes nodes
  version: v1.0.1
status:
  source:
    name: default
