apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: krew
spec:
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    To list krew commands and to get help, run:
      $ kubectl krew
    For a full list of available plugins, run:
      $ kubectl krew search

    You can find documentation at
      https://krew.sigs.k8s.io/docs/user-guide/quickstart/.
  homepage: https://krew.sigs.k8s.io/
  platforms:
  - bin: krew
    files:
    - from: ./krew-darwin_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 039fbb18c784f6b097b7ee6d048d36dfdb055c6e3a7c76e7251536594d6027a2
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.0/krew.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 039fbb18c784f6b097b7ee6d048d36dfdb055c6e3a7c76e7251536594d6027a2
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.0/krew.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_arm
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm
        os: linux
    sha256: 039fbb18c784f6b097b7ee6d048d36dfdb055c6e3a7c76e7251536594d6027a2
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.0/krew.tar.gz
  - bin: krew.exe
    files:
    - from: ./krew-windows_amd64.exe
      to: krew.exe
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 039fbb18c784f6b097b7ee6d048d36dfdb055c6e3a7c76e7251536594d6027a2
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.0/krew.tar.gz
  shortDescription: Package manager for kubectl plugins.
  version: v0.4.0
status:
  source:
    name: default
