apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: rbac-view
spec:
  caveats: |
    Run "kubectl rbac-view" to open a browser with an html view of your permissions.
  homepage: https://github.com/jasonrichardsmith/rbac-view
  platforms:
  - bin: rbac-view
    files:
    - from: bin/darwin/rbac-view
      to: rbac-view
    - from: LICENSE
      to: LICENSE
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 0a042551e9fa8255227292a5ff74073ea67efd98fde9bab4f4c0709e1f3d19c1
    uri: https://github.com/jasonrichardsmith/rbac-view/releases/download/v0.2.1/rbac-view.v0.2.1.darwin.tar.gz
  - bin: rbac-view
    files:
    - from: bin/linux/rbac-view
      to: rbac-view
    - from: LICENSE
      to: LICENSE
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: fc20abf295d3e6f012e45e5b5f04b316e57b5858e9bcec0a9b19c0db47b0ba07
    uri: https://github.com/jasonrichardsmith/rbac-view/releases/download/v0.2.1/rbac-view.v0.2.1.linux.tar.gz
  - bin: rbac-view
    files:
    - from: bin/windows/rbac-view
      to: rbac-view
    - from: LICENSE
      to: LICENSE
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 5fb66464cfe1a32930d62f16f6bc642e61577a74cf0bc6178dd59b2a710c617a
    uri: https://github.com/jasonrichardsmith/rbac-view/releases/download/v0.2.1/rbac-view.v0.2.1.windows.tar.gz
  shortDescription: A tool to visualize your RBAC permissions.
  version: v0.2.1
status:
  source:
    name: default
