apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: restart
spec:
  description: |
    Restarts a pod with the given name. The existing pod
    will be deleted and created again, not a true restart.
  homepage: https://github.com/achanda/kubectl-restart
  platforms:
  - bin: restart.sh
    files:
    - from: /kubectl-restart-*/restart.sh
      to: .
    - from: /kubectl-restart-*/LICENSE
      to: .
    selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    sha256: d7079b79bf4e10e55ded435a2e862efe310e019b6c306a8ff04191238ef4b2b4
    uri: https://github.com/achanda/kubectl-restart/archive/v0.0.3.zip
  shortDescription: Restarts a pod with the given name
  version: v0.0.1
status:
  source:
    name: default
