apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: view-secret
spec:
  description: |
    Base64 decode by key or all key/value pairs in a given secret.

    # print secret keys
    $ kubectl view-secret <secret>

    # decode specific entry
    $ kubectl view-secret <secret> <key>

    # decode all secret contents
    $ kubectl view-secret <secret> -a/--all

    # print keys for secret in different namespace
    $ kubectl view-secret <secret> -n/--namespace foo

    # print keys for secret in different context
    $ kubectl view-secret <secret> -c/--context ctx

    # print keys for secret by providing kubeconfig
    $ kubectl view-secret <secret> -k/--kubeconfig <cfg>

    # suppress info output
    $ kubectl view-secret <secret> -q/--quiet
  homepage: https://github.com/elsesiy/kubectl-view-secret
  platforms:
  - bin: kubectl-view-secret
    files:
    - from: kubectl-view-secret
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 5c0190d56df68c19fc6af7d9a9e0593b594aa83a0f2d5567e4385058a09cba9a
    uri: https://github.com/elsesiy/kubectl-view-secret/releases/download/v0.6.0/kubectl-view-secret_0.6.0_Darwin_x86_64.tar.gz
  - bin: kubectl-view-secret
    files:
    - from: kubectl-view-secret
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: d49b796a212a3eab8de75291c7321de738140b6f24be5f350706bbd563ef414d
    uri: https://github.com/elsesiy/kubectl-view-secret/releases/download/v0.6.0/kubectl-view-secret_0.6.0_Linux_x86_64.tar.gz
  - bin: kubectl-view-secret.exe
    files:
    - from: kubectl-view-secret.exe
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 330cfaddc44fdf110860866da07f45ceb4e3c59a11b9c11483fd24968d32bfb1
    uri: https://github.com/elsesiy/kubectl-view-secret/releases/download/v0.6.0/kubectl-view-secret_0.6.0_Windows_x86_64.tar.gz
  shortDescription: Decode Kubernetes secrets
  version: v0.6.0
status:
  source:
    name: default
